project:
  type: website
  output-dir: docs

website:
  title: "Hanan Ather"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: My Writing
      - href: principles.qmd
        text: About

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    google-fonts: ["Inter:400,500,700", "Merriweather:400,700"]
    toc: false
    toc-float: false
    toc-expand: 3
    toc-title: "Table of Contents"

execute:
  freeze: auto
